#See https://github.com/zricethezav/gitleaks#configuration

title = "Foundry Template"

[extend]
useDefault = true

[[rules]]
id = "ethereum-rule-1"
description = "Ethereum private keys"
regex = '''(?:\'|"|\s|^)(?:0x)?[a-fA-F0-9]{64}(?:\'|"|\s|;|$)'''


[allowlist]
paths = [
  '''lib/forge-std/(.*?)''',
  '''lib/openzeppelin-contracts/(.*?)''',
  '''lib/prb-math/(.*?)''',
  '''lib/openzeppelin-contracts-upgradeable/(.*?)''',
  '''out/(.*?)''',
  '''cache/(.*?)''',
  '''node_modules/(.*?)''',
  '''test/utils/Addresses.sol''',
  '''test/pricing/TellorValueProvider.t.sol''',
]
