[profile.default]
name = 'contracts-template'
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
