name: "CI"

on:
  workflow_dispatch:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "!main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint commits - PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        if: github.event_name == 'pull_request'

      - name: Lint commits - Push
        run: echo "$(git log -1 --format='%s')" | npx commitlint
        if: github.event_name != 'pull_request'

      - name: Lint
        run: npm run lint

      - name: Formatting
        run: npm run format:verify

      - name: "Generate fuzz seed"
        run: echo "FOUNDRY_FUZZ_SEED=$(echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800)))" >> $GITHUB_ENV

      - name: Run tests
        run: npm run test

      - name: "Check that the contracts are each under 24kB"
        run: |
          forge --version
          forge build --sizes

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.

      - name: Security scan - Slither
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
          solc-select install 0.8.17
          solc-select use 0.8.17
          slither .
